apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
spec:
  selector:
    matchLabels:
      name: DEPLOYMENT_INFORMATION
  template:
    metadata:
      labels:
        name: DEPLOYMENT_INFORMATION
    spec:
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR # Replace with actual node
      containers:
      - name: cosmos-nim
        image: nvcr.io/nim/nvidia/cosmos-predict1-7b-text2world:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ngc-api-secret       # Name of the Kubernetes secret
              key: NGC_API_KEY           # Key inside the secret containing your API key
        volumeMounts:
        - name: nim-cache
          mountPath: /opt/nim/.cache
        resources:
          limits:
            nvidia.com/gpu: GPU_LIMIT
            cpu: CPU_LIMIT
            memory: MEMORY_LIMIT
            ephemeral-storage: STORAGE_LIMIT
          requests:
            nvidia.com/gpu: GPU_REQUEST
            cpu: CPU_REQUEST
            memory: MEMORY_REQUEST
            ephemeral-storage: STORAGE_REQUEST
      volumes:
      - name: nim-cache
        emptyDir: {}
      imagePullSecrets:
      - name: sercret-nvidia
      restartPolicy: Always
