apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
spec:
  selector:
    matchLabels:
      name: DEPLOYMENT_INFORMATION
  template:
    metadata:
      labels:
        name: DEPLOYMENT_INFORMATION
    spec:
      dnsPolicy: "None"                    # Required when overriding dnsConfig
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 1.1.1.1
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR
      containers:
      - name: cosmos-nim
        image: nvcr.io/nim/nvidia/cosmos-predict1-7b-text2world:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: NGC_API_KEY
          value: "eyJhdXRocyI6eyJudmNyLmlvIjp7InVzZXJuYW1lIjoiJG9hdXRodG9rZW4iLCJwYXNzd29yZCI6ImJuWm1jSE15YVd3MFpEUTFPR3B0YUhGMk9HcHdhR0V5TWpjNk1qWXhNRFZoWlRZdE1HRTRZUzAwWWpCakxXRTFZVFF0WW1Zek5qRmhabVEwTXpBeiJ9fX0="
        volumeMounts:
        - name: nim-cache
          mountPath: /opt/nim/.cache
        resources:
          limits:
            nvidia.com/gpu: GPU_LIMIT
            cpu: CPU_LIMIT
            memory: MEMORY_LIMIT
            ephemeral-storage: STORAGE_LIMIT
          requests:
            nvidia.com/gpu: GPU_REQUEST
            cpu: CPU_REQUEST
            memory: MEMORY_REQUEST
            ephemeral-storage: STORAGE_REQUEST
      volumes:
      - name: nim-cache
        emptyDir: {}
      imagePullSecrets:
      - name: sercret-nvidia
      restartPolicy: Always
