apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-cosmos
spec:
  selector:
    matchLabels:
      name: DEPLOYMENT_INFORMATION
  template:
    metadata:
      labels:
        name: DEPLOYMENT_INFORMATION
    spec:
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR
      containers:
      - name: cosmos-nim
        image: nvcr.io/nim/nvidia/cosmos-predict1-7b-text2world:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ngc-api-secret        # This is your pull secret AND API key holder
              key: NGC_API_KEY             # Make sure this key exists in the secret!
        volumeMounts:
        - name: nim-cache
          mountPath: /opt/nim/.cache
        resources:
          limits:
            nvidia.com/gpu: GPU_LIMIT
            cpu: CPU_LIMIT
            memory: MEMORY_LIMIT
            ephemeral-storage: STORAGE_LIMIT
          requests:
            nvidia.com/gpu: GPU_REQUEST
            cpu: CPU_REQUEST
            memory: MEMORY_REQUEST
            ephemeral-storage: STORAGE_REQUEST
      volumes:
      - name: nim-cache
        emptyDir: {}
      imagePullSecrets:
      - name: sercret-nvidia              # This allows pulling from nvcr.io
      restartPolicy: Always
