apiVersion: v1
kind: Service
metadata:
  name: nim-cosmos-service
spec:
  selector:
    deploymentInformation: DEPLOYMENT_INFORMATION # This is a placeholder that will get replaced
  ports:
  - protocol: TCP
    port: 80 # Port on the service
    targetPort: 8000 # Port on the pods
  type: ClusterIP
