apiVersion: v1
kind: Service
metadata:
  name: value-service
spec:
  selector:
    deploymentInformation: value-service
  ports:
  - protocol: TCP
    port: 8080 # Port on the service
    targetPort: 8080 # Port on the pods
  type: NodePort
